'use strict';
const assert=require('node:assert/strict');global.window={};
for(const name of ['catalog','effects','progression','settlement','personal','warfare','vehicles','actors','neural','autoplay','destruction','stories','world','engine'])require('../src/'+name+'.js');
const {Engine:E,Autoplay:A,Neural:N}=window.Sirens;let passed=0;
function check(name,fn){fn();passed++;console.log('PASS '+name);}
function fixture(){const s=E.create(42,'calm','rescue');s.tiles.fill(0);s.containers=[];s.zombies=[];s.humans=[];s.vehicles=[];s.buildings=[];s.structures=[];s.player.x=336;s.player.y=336;s.player.inventory={bat:1,food:2,water:2,bandage:1};return s;}
function action(s,c){if(c==='interact')return E.interact(s);if(c.startsWith('craft:'))return E.craft(s,c.slice(6));return E.action(s,c);}
function run(s,p,frames){for(let i=0;i<frames;i++){const out=A.step(p,s,1/60);if(out.command)action(s,out.command);E.update(s,1/60,out.input);}}
check('network training changes real weights and lowers unseen synthetic prediction error',()=>{const model=N.create(42),trained=N.prepare(42);let raw=0,learned=0;for(let i=0;i<96;i++){const x=[i%4===0?1:0,(i%11)/11,Math.sin(i*7),Math.cos(i*3),.4,(i%8)/8],target=N.teacher(x);raw+=(N.predict(model,x)-target)**2;learned+=(N.predict(trained,x)-target)**2;}assert.equal(trained.weights.length,65);assert.equal(trained.samples,3072);assert(learned<raw*.25,JSON.stringify({raw,learned}));assert.notDeepEqual(model.weights,trained.weights);assert.deepEqual(N.prepare(42),trained);});
check('online backpropagation changes bounded finite weights and rejects unstable input',()=>{const m=N.prepare(4),before=m.weights.slice();for(let i=0;i<500;i++)N.learn(m,[NaN,Infinity,1,-1,.5,1],-1,.015);assert.notDeepEqual(m.weights,before);assert(m.weights.every(w=>Number.isFinite(w)&&Math.abs(w)<=4));assert(Number.isFinite(N.predict(m,[undefined])));assert.equal(N.summary(m).parameters,65);});
check('AI starts disabled, toggle hands control back without mutating the world',()=>{const s=fixture(),p=A.create(),before=E.serialize(s);assert(!A.status(p).enabled);assert.equal(A.step(p,s,.1).command,undefined);assert.equal(E.serialize(s),before);assert(A.toggle(p));const out=A.step(p,s,.016);assert(out.input);assert.equal(E.serialize(s),before);assert.equal(A.toggle(p,false),false);});
check('AI actually loots and opens a closed door using paid production commands',()=>{const s=fixture(),p=A.create();s.containers=[{id:'supplies-0',label:'Test cabin supplies',x:400,y:336,items:{scrap:2},looted:false}];for(let y=0;y<s.height;y++)s.tiles[y*s.width+11]=3;s.tiles[10*s.width+11]=6;s._doorHealth[10*s.width+11]=65;A.toggle(p);run(s,p,240);assert.equal(s.tiles[10*s.width+11],7);assert(s.player.inventory.scrap>0);assert(s.containers[0].looted);assert(p.commands<15);});
check('AI uses carried supplies and never grants unowned healing or equipment',()=>{const s=fixture(),p=A.create();s.player.thirst=80;s.player.hunger=80;s.player.health=50;s.player.bleeding=1;A.toggle(p);run(s,p,100);assert(s.player.health>50);assert(s.player.thirst<80);assert(s.player.hunger<80);assert((s.player.inventory.bandage||0)<1);assert((s.player.inventory.water||0)<2);assert((s.player.inventory.food||0)<2);assert(s.player.inventory[s.player.weapon]>0);});
check('AI dismisses or recruits through real conversations instead of stalling on the modal',()=>{const s=fixture(),p=A.create(),h={id:'h:0,0:0',x:370,y:336,health:100,faction:'survivor',following:false,name:'Morgan',weapon:'bat',angle:0,cooldown:0};s.humans=[h];s.player.inventory.food=5;assert(window.Sirens.Actors.interact(s));A.toggle(p);for(let i=0;i<90;i++){const out=A.step(p,s,1/60);if(out.command)action(s,out.command);}assert.equal(s.conversation,null);assert(h.following);assert.equal(s.player.inventory.food,4);});
check('neural inference selects legal movement and learns from actual movement feedback',()=>{const s=fixture(),p=A.create();s.containers=[{id:'supplies-0',label:'Far supplies',x:700,y:336,items:{scrap:2},looted:false}];A.toggle(p);run(s,p,150);const status=A.status(p);assert(status.neural.feedback>0);assert(status.neural.samples>3072);assert(status.choices.length===8);assert(status.choices.every(c=>Number.isFinite(c.score)&&Math.abs(c.score)<=1));assert(s.player.x>350);assert(!E.isSolid(s,s.player.x/32,s.player.y/32));});
check('AI stops at death and caps command rate, route history, and invalid timing',()=>{const s=fixture(),p=A.create();A.toggle(p);A.step(p,s,NaN);assert.equal(p.clock,0);run(s,p,300);assert(p.commands<=16);assert(Object.keys(p.visited).length<=128);assert(Object.keys(p.blocked).length<=128);s.player.health=0;A.step(p,s,.01);assert(!A.status(p).enabled);});
check('AI sets aside supplies it cannot carry and heals with health-only remedies instead of repeating failed commands',()=>{const s=fixture(),p=A.create();s.player.inventory={bat:1,wood:26};s.containers=[{id:'supplies-0',label:'Near woodpile',x:400,y:336,items:{wood:5},looted:false},{id:'supplies-1',label:'Far bandage',x:900,y:336,items:{bandage:1},looted:false}];A.toggle(p);let tries=0;for(let i=0;i<60*40;i++){const out=A.step(p,s,1/60);if(out.command==='interact')tries++;if(out.command)action(s,out.command);E.update(s,1/60,out.input);}assert(s.containers.every(c=>c.id!=='supplies-1'||c.looted),'the pilot moves on to supplies it can carry');assert.equal(s.player.inventory.bandage,1);assert(tries<20,'failed collection attempts are bounded: '+tries);
const w=fixture(),q=A.create(),seen={};w.player.health=55;w.player.inventory={bat:1,painkillers:1};w.containers=[{id:'supplies-0',label:'Scrap',x:700,y:336,items:{scrap:1},looted:false}];A.toggle(q);for(let i=0;i<60*20;i++){const out=A.step(q,w,1/60);if(out.command){seen[out.command]=(seen[out.command]||0)+1;action(w,out.command);}E.update(w,1/60,out.input);}assert.equal(seen.bandage,undefined,'no bandage command without a bleeding dressing');assert.equal(seen['use:painkillers'],1);assert(!w.player.inventory.painkillers);assert(w.player.health>58);assert(w.containers[0].looted,'the wounded pilot keeps scavenging');});
console.log(passed+' neural and autoplay checks passed.');
