'use strict';
const assert = require('node:assert/strict');
global.window = {};
for (const name of ['catalog','effects','progression','settlement','personal','warfare','vehicles','actors','destruction','stories','world','engine']) require('../src/' + name + '.js');
const { Engine:E, Actors:A, Progression:P, World:W } = window.Sirens;
let passed=0;
function check(name,fn){fn();passed++;console.log('PASS '+name);}
function fixture(mode='rescue') { const s=E.create(42,'standard',mode);s.tiles.fill(0);s.buildings=[];s.structures=[];s.zombies=[];s.humans=[];s.vehicles=[];s.containers=[];s.player.x=mode==='openworld'?3072:1008;s.player.y=s.player.x;return s; }
function human(s,id='h:0,0:0',weapon='bat') { const h={id,x:s.player.x+32,y:s.player.y,health:100,angle:0,faction:'survivor',following:false,name:'Morgan',weapon,cooldown:0};s.humans.push(h);return h; }
check('killed survivors drop actual weapons, finite stock, food and water once',()=>{const s=fixture(),h=human(s);const c=P.contact(s,h);c.stock=1;A.hit(s,h,100,true);assert.equal(h.health,0);assert.equal(s.containers.length,1);assert.deepEqual(s.containers[0].items,{bat:1,food:1,water:1,bandage:1});const before=JSON.stringify(s.containers);A.hit(s,h,100,true);A.update(s,.05);assert.equal(JSON.stringify(s.containers),before);assert(c.deathLooted);assert.equal(c.stock,0);assert.equal(c.alive,false);});
check('raider pistols and ammunition become collectible through E, with full packs leaving loot',()=>{const s=fixture(),h=human(s,'h:0,0:1','pistol');h.faction='raider';A.hit(s,h,100,false);assert.equal(s.containers[0].items.ammo,6);s.player.inventory={wood:30};assert.equal(E.interact(s),false);s.player.inventory={};assert(E.interact(s));assert.equal(s.player.inventory.pistol,1);assert.equal(s.player.inventory.ammo,6);assert(!s.containers.some(c=>c._ground),'an emptied body drop is removed');assert.equal(P.ensure(s).insight,0,'body drops cannot farm research');});
check('successful robbery gives one surrendered bag and killing later cannot duplicate its supplies',()=>{const s=fixture(),h=human(s);s.player.inventory={pistol:1};s.player.weapon='pistol';assert(A.interact(s));assert(E.action(s,'robSurvivor'));const c=P.contact(s,h);assert(c.robbed);assert.equal(c.stock,0);assert.equal(h.faction,'raider');assert.equal(s.conversation,null);assert.deepEqual(s.containers[0].items,{food:1,water:1,bandage:3});assert.equal(E.action(s,'robSurvivor'),false);A.hit(s,h,100,true);assert.deepEqual(s.containers[0].items,{food:1,water:1,bandage:3,bat:1});s.day++;P.contact(s,h);assert.equal(c.stock,0);});
check('resolute survivors can reject weak threats and no robbery works from stale remote conversations',()=>{const s=fixture(),h=human(s);P.contact(s,h).trait='resolute';s.player.inventory={bat:1};s.player.weapon='bat';assert(A.interact(s));assert(E.action(s,'robSurvivor'));assert.equal(s.containers.length,0);assert.equal(h.faction,'raider');const other=human(s,'h:0,0:1');assert(A.interact(s));s.player.x-=200;assert.equal(E.action(s,'trade'),false);assert.equal(E.action(s,'robSurvivor'),false);});
check('neutral survivors flee nearby undead while recruited companions defend',()=>{const s=fixture(),h=human(s);const z={id:1,x:h.x+90,y:h.y,health:100};s.zombies=[z];const initial=Math.hypot(h.x-z.x,h.y-z.y);A.update(s,.1);assert(Math.hypot(h.x-z.x,h.y-z.y)>initial);assert.equal(A.activity(s,h),'Fleeing danger');h.following=true;z.x=h.x+30;A.update(s,.1);assert(z.health<100);});
check('human fight noise produces bounded undead response, quiet rescue mode does not',()=>{const s=fixture('openworld');s._chaosClock=12;s.noises=[{x:s.player.x,y:s.player.y,radius:480,life:3}];E.update(s,.05,{});assert(s.zombies.length>0&&s.zombies.length<=3);assert.equal(s._chaosClock,0);const quiet=fixture();quiet._chaosClock=12;quiet.noises=[{x:quiet.player.x,y:quiet.player.y,radius:480,life:3}];E.update(quiet,.05,{});assert.equal(quiet.zombies.length,0);});
check('regular open world migration brings nearby undead without exceeding active budgets',()=>{const s=fixture('openworld');s._ecologyClock=24;E.update(s,.05,{});assert(s.zombies.length>0&&s.zombies.length<=4);s.zombies=Array.from({length:360},(_,i)=>({id:'wave:42:'+i,x:4000,y:4000,health:64,state:'wander',angle:0,windup:0,_targetX:4000,_targetY:4000,_lastSeen:-100,_wanderClock:5,_path:[],_pathClock:0,_stun:0,_attackCooldown:0,_blockedTimer:0}));s._ecologyClock=24;s._chaosClock=12;E.update(s,.05,{});assert.equal(s.zombies.length,360);});
check('new road sectors hold larger seeded undead populations without changing terrain reproducibility',()=>{for(const [difficulty,count]of[['calm',8],['standard',15],['hard',22]]){const a=W.generate(42,difficulty,1,0),b=W.generate(42,difficulty,1,0);assert.equal(a.zombies.length,count);assert.deepEqual(a,b);}});
check('corpse drops and robbery history survive generated saves without resurrecting possessions',()=>{for(const mode of ['rescue','openworld']){const s=E.create(42,'calm',mode),h=s.humans[0];s.player.x=h.x-32;s.player.y=h.y;s.player.inventory={pistol:1};E.action(s,'equip:pistol');if(E.isSolid(s,h.x/32,h.y/32)) continue;P.contact(s,h);A.hit(s,h,100,true);const saved=E.serialize(s),restored=E.deserialize(saved);assert(restored.progression.contacts[h.id].deathLooted);const before=JSON.stringify(restored.containers);A.update(restored,.05);assert.equal(JSON.stringify(restored.containers),before);const damaged=JSON.parse(saved);damaged.state.progression.contacts[h.id].robbed='yes';assert.throws(()=>E.deserialize(JSON.stringify(damaged)));}});
check('emptied ground piles leave the area pile budget, so drops and belongings stay local and older saves still load',()=>{
  const s=fixture('openworld');s.player.inventory={bandage:61};
  for(let i=0;i<60;i++){s.player.x=1000+(i%10)*96;s.player.y=1000+Math.floor(i/10)*96;assert(E.action(s,'drop:bandage'));assert(E.interact(s));}
  assert.equal(s.containers.filter(c=>c._ground).length,0,'emptied piles are removed');
  s.player.x=3072;s.player.y=3072;assert(E.action(s,'drop:bandage'),'a 61st drop still has room');
  const h=human(s);A.hit(s,h,100,true);const bag=s.containers.find(c=>c.items.food);assert(bag&&Math.hypot(bag.x-h.x,bag.y-h.y)<=48,'belongings stay beside the body');
  const g=E.create(42,'calm','openworld');g.zombies=[];g.player.inventory.bandage=1;assert(E.action(g,'drop:bandage'));
  const doc=JSON.parse(E.serialize(g)),record=Object.values(doc.world.records).find(r=>(r.ground||[]).length);
  record.ground.push(Object.assign({},record.ground[0],{id:'drop:42:9999',items:{},looted:true}));
  const loaded=E.deserialize(JSON.stringify(doc));assert(!loaded.containers.some(c=>c.id==='drop:42:9999'));assert(loaded.containers.some(c=>c._ground&&c.items.bandage===1));
});
console.log(passed+' living world and raider checks passed.');
