'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {WebSocket}=require('ws');const{createServer}=require('../server/index.cjs');const{createDirectory}=require('../server/directory.cjs');
const delay=ms=>new Promise(r=>setTimeout(r,ms));let passed=0;async function check(name,fn){await fn();passed++;console.log('PASS '+name);}
async function client(url,token,name,identity=null){const socket=new WebSocket(url),messages=[];socket.on('error',()=>{});socket.on('message',data=>messages.push(JSON.parse(data)));await new Promise((resolve,reject)=>{socket.once('open',resolve);socket.once('error',reject);});socket.send(JSON.stringify({type:'join',protocol:1,token,name,identity}));const c={socket,messages,seq:0,async wait(type,predicate=()=>true){for(let i=0;i<100;i++){const m=messages.find(m=>m.type===type&&predicate(m));if(m)return m;await delay(10);}throw new Error('No '+type+': '+JSON.stringify(messages.filter(m=>m.type!=='snapshot')));},send(action){const seq=++this.seq;socket.send(JSON.stringify({type:'action',seq,action}));return seq;},input(input={}){socket.send(JSON.stringify({type:'input',seq:++this.seq,moveX:0,moveY:0,sprint:false,sneak:false,attack:false,shoot:false,...input}));},close(){socket.close();}};return c;}
(async()=>{const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'sirens-mp-'));let host,directory;const clients=[];try{
 await check('twenty real WebSocket players join a public local host and a twenty-first is denied',async()=>{host=await createServer({port:0,public:true,autoTick:false,seed:0,difficulty:'calm',worldFile:path.join(temporary,'world.save.json')});for(let i=0;i<20;i++){const c=await client(host.url,'','Player '+i);clients.push(c);c.welcome=await c.wait('welcome');}assert.equal(host.getPlayers().filter(p=>p.connected).length,20);const overflow=await client(host.url,'','Overflow');clients.push(overflow);assert.match((await overflow.wait('error')).message,/twenty/);assert.equal((await(await fetch(host.httpUrl+'health')).json()).capacity,20);});
 await check('shared container loot transfers once across separate player packs',async()=>{const a=clients[0],b=clients[1];const before=host.getPlayers();const seqA=a.send('interact'),seqB=b.send('interact');await a.wait('ack',m=>m.seq===seqA);await b.wait('ack',m=>m.seq===seqB);const after=host.getPlayers();let delta=0;for(let i=0;i<2;i++)for(const[id,n]of Object.entries(after[i].player.inventory))delta+=n-(before[i].player.inventory[id]||0);assert(delta>0,JSON.stringify({before:before.slice(0,2),after:after.slice(0,2),ackA:a.messages.filter(m=>m.type==='ack'),ackB:b.messages.filter(m=>m.type==='ack'),containers:host.getState().containers.filter(c=>c.label.includes('cabin'))}));assert.notDeepEqual(after[0].player.inventory,after[1].player.inventory);});
 await check('host advances one shared clock while all twenty players keep independent actual movement and needs',async()=>{for(const c of clients.slice(0,20))c.input({moveX:1});await delay(30);const before=host.getPlayers(),elapsed=host.getState().elapsed;const started=performance.now();for(let i=0;i<20;i++)host.tick();const cost=(performance.now()-started)/20;const after=host.getPlayers();assert(Math.abs(host.getState().elapsed-elapsed-1)<.0001);assert(after.every((r,i)=>r.player.x>before[i].player.x+3));assert(after.every((r,i)=>r.player.thirst>before[i].player.thirst));console.log('20-player tick fixture average '+cost.toFixed(2)+' ms (local loopback, not an internet load test).');});
 await check('snapshot lists all twenty survivors and ignores client attempts to set inventory',async()=>{const c=clients[2];host.snapshot();const snapshot=await c.wait('snapshot',m=>m.players.length===20);assert.equal(snapshot.players.length,20);const inv=host.getPlayers()[2].player.inventory;c.socket.send(JSON.stringify({type:'input',seq:++c.seq,moveX:0,moveY:0,inventory:{food:1000}}));assert.match((await c.wait('error')).message,/Invalid/);await delay(30);assert.deepEqual(host.getPlayers()[2].player.inventory,inv);});
 await check('repeated action sequences are rejected without spending supplies twice',async()=>{const c=clients[0],seq=c.send('drop:food');const ack=await c.wait('ack',m=>m.seq===seq);assert(ack.ok);const after=host.getPlayers()[0].player.inventory.food||0;c.socket.send(JSON.stringify({type:'action',seq,action:'drop:food'}));await c.wait('error');await delay(30);assert.equal(host.getPlayers()[0].player.inventory.food||0,after);});
 await check('ground floor guards and stale input checks are enforced by the host',async()=>{const c=clients[3],seq=c.send('stairsUp');assert.equal((await c.wait('ack',m=>m.seq===seq)).ok,false);c.input({moveX:1});await delay(650);const x=host.getPlayers()[3].player.x;host.tick();assert.equal(host.getPlayers()[3].player.x,x);});
 await check('server restart restores shared edits and the same survivor pack using opaque private identity',async()=>{const identity=clients[1].welcome.identity,id=clients[1].welcome.id,pack=host.getPlayers().find(r=>r.id===id).player.inventory;await host.save();await host.close();host=await createServer({port:0,public:true,autoTick:false,worldFile:path.join(temporary,'world.save.json')});const c=await client(host.url,'','Beta',identity);clients.push(c);assert.equal((await c.wait('welcome')).id,id);assert.deepEqual(host.getPlayers().find(r=>r.id===id).player.inventory,pack);const saved=fs.readFileSync(path.join(temporary,'world.save.json'),'utf8');assert(!saved.includes(identity),'raw bearer identity must not be stored on disk');});
 await check('private local lobbies reject empty keys, issue invite codes, and remain absent from public listings',async()=>{const privateHost=await createServer({port:0,autoTick:false,worldFile:path.join(temporary,'private.save.json')});try{assert(privateHost.invite.startsWith('SIRENS1.'));const data=JSON.parse(Buffer.from(privateHost.invite.slice(8),'base64url').toString());const wrong=await client(privateHost.url,'','No key');clients.push(wrong);await wrong.wait('error');const good=await client(privateHost.url,data.token,'Invited');clients.push(good);await good.wait('welcome');assert.equal((await(await fetch(privateHost.httpUrl+'servers')).json()).servers.length,0);}finally{await privateHost.close();}});
 await check('public directory registers authorized real hosts, exposes no keys, persists and expires listings',async()=>{let now=Date.now();const token='directory-test-key-only';directory=await createDirectory({port:0,token,file:path.join(temporary,'directory.json'),now:()=>now});const publicData=(await(await fetch(host.httpUrl+'servers')).json()).servers[0];assert(publicData.public);const unauthorized=await fetch(directory.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(publicData)});assert.equal(unauthorized.status,403);const registered=await fetch(directory.url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(publicData)});assert.equal(registered.status,201);const listed=await(await fetch(directory.url)).json();assert.equal(listed.servers.length,1);assert(!JSON.stringify(listed).includes(token));await directory.close();directory=await createDirectory({port:0,token,file:path.join(temporary,'directory.json'),now:()=>now});assert.equal((await(await fetch(directory.url)).json()).servers.length,1);now+=180001;assert.equal((await(await fetch(directory.url)).json()).servers.length,0);});
 console.log(passed+' multiplayer and directory checks passed.');
}finally{for(const c of clients)c.close();if(host)await host.close();if(directory)await directory.close();fs.rmSync(temporary,{recursive:true,force:true});}})().catch(error=>{console.error(error.stack);process.exitCode=1;});
