'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {WebSocket}=require('ws');const net=require('node:net'),crypto=require('node:crypto');const{createServer}=require('../server/index.cjs');const{createDirectory}=require('../server/directory.cjs');
const delay=ms=>new Promise(r=>setTimeout(r,ms));let passed=0;async function check(name,fn){await fn();passed++;console.log('PASS '+name);}
function upgrade(port,localAddress){return new Promise(resolve=>{const s=net.connect({port,host:'127.0.0.1',localAddress},()=>s.write('GET /game HTTP/1.1\r\nHost: 127.0.0.1\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: '+crypto.randomBytes(16).toString('base64')+'\r\nSec-WebSocket-Version: 13\r\n\r\n'));s.on('error',error=>resolve({s,status:error.code}));s.once('data',d=>resolve({s,status:String(d).split(' ')[1],opened:Date.now()}));});}
async function outcome(c){for(let i=0;i<300;i++){const m=c.messages.find(m=>m.type==='welcome'||m.type==='error');if(m)return m;await delay(10);}throw new Error('No join outcome');}
async function client(url,token,name,identity=null,ownerToken){const socket=new WebSocket(url),messages=[];socket.on('error',()=>{});socket.on('message',data=>messages.push(JSON.parse(data)));await new Promise((resolve,reject)=>{socket.once('open',resolve);socket.once('error',reject);});socket.send(JSON.stringify({type:'join',protocol:1,token,name,identity,...(ownerToken?{ownerToken}:{})}));const c={socket,messages,seq:0,async wait(type,predicate=()=>true){for(let i=0;i<100;i++){const m=messages.find(m=>m.type===type&&predicate(m));if(m)return m;await delay(10);}throw new Error('No '+type+': '+JSON.stringify(messages.filter(m=>m.type!=='snapshot')));},send(action){const seq=++this.seq;socket.send(JSON.stringify({type:'action',seq,action}));return seq;},chat(text){const seq=++this.seq;socket.send(JSON.stringify({type:'chat',seq,text}));return this.wait('command-result',m=>m.seq===seq);},input(input={}){socket.send(JSON.stringify({type:'input',seq:++this.seq,moveX:0,moveY:0,sprint:false,sneak:false,attack:false,shoot:false,...input}));},close(){socket.close();}};return c;}
(async()=>{const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'sirens-mp-'));let host,directory;const clients=[];try{
 await check('twenty real WebSocket players join a public local host and a twenty-first is denied',async()=>{host=await createServer({port:0,public:true,autoTick:false,seed:0,difficulty:'calm',worldFile:path.join(temporary,'world.save.json')});for(let i=0;i<20;i++){const c=await client(host.url,'','Player '+i);clients.push(c);c.welcome=await c.wait('welcome');}assert.equal(host.getPlayers().filter(p=>p.connected).length,20);const overflow=await client(host.url,'','Overflow');clients.push(overflow);assert.match((await overflow.wait('error')).message,/twenty/);assert.equal((await(await fetch(host.httpUrl+'health')).json()).capacity,20);});
 await check('shared container loot transfers once across separate player packs',async()=>{const a=clients[0],b=clients[1];const before=host.getPlayers();const seqA=a.send('interact'),seqB=b.send('interact');await a.wait('ack',m=>m.seq===seqA);await b.wait('ack',m=>m.seq===seqB);const after=host.getPlayers();let delta=0;for(let i=0;i<2;i++)for(const[id,n]of Object.entries(after[i].player.inventory))delta+=n-(before[i].player.inventory[id]||0);assert(delta>0,JSON.stringify({before:before.slice(0,2),after:after.slice(0,2),ackA:a.messages.filter(m=>m.type==='ack'),ackB:b.messages.filter(m=>m.type==='ack'),containers:host.getState().containers.filter(c=>c.label.includes('cabin'))}));assert.notDeepEqual(after[0].player.inventory,after[1].player.inventory);});
 await check('host advances one shared clock while all twenty players keep independent actual movement and needs',async()=>{for(const c of clients.slice(0,20))c.input({moveX:1});await delay(30);const before=host.getPlayers(),elapsed=host.getState().elapsed;const started=performance.now();for(let i=0;i<20;i++)host.tick();const cost=(performance.now()-started)/20;const after=host.getPlayers();assert(Math.abs(host.getState().elapsed-elapsed-1)<.0001);assert(after.every((r,i)=>r.player.x>before[i].player.x+3));assert(after.every((r,i)=>r.player.thirst>before[i].player.thirst));console.log('20-player tick fixture average '+cost.toFixed(2)+' ms (local loopback, not an internet load test).');});
 await check('snapshot lists all twenty survivors and ignores client attempts to set inventory',async()=>{const c=clients[2];host.snapshot();const snapshot=await c.wait('snapshot',m=>m.players.length===20);assert.equal(snapshot.players.length,20);const inv=host.getPlayers()[2].player.inventory;c.socket.send(JSON.stringify({type:'input',seq:++c.seq,moveX:0,moveY:0,inventory:{food:1000}}));assert.match((await c.wait('error')).message,/Invalid/);await delay(30);assert.deepEqual(host.getPlayers()[2].player.inventory,inv);});
 await check('repeated action sequences are rejected without spending supplies twice',async()=>{const c=clients[0],seq=c.send('drop:food');const ack=await c.wait('ack',m=>m.seq===seq);assert(ack.ok);const after=host.getPlayers()[0].player.inventory.food||0;c.socket.send(JSON.stringify({type:'action',seq,action:'drop:food'}));await c.wait('error');await delay(30);assert.equal(host.getPlayers()[0].player.inventory.food||0,after);});
 await check('ground floor guards and stale input checks are enforced by the host',async()=>{const c=clients[3],seq=c.send('stairsUp');assert.equal((await c.wait('ack',m=>m.seq===seq)).ok,false);c.input({moveX:1});await delay(650);const x=host.getPlayers()[3].player.x;host.tick();assert.equal(host.getPlayers()[3].player.x,x);});
 await check('server restart restores shared edits and the same survivor pack using opaque private identity',async()=>{const identity=clients[1].welcome.identity,id=clients[1].welcome.id,pack=host.getPlayers().find(r=>r.id===id).player.inventory;await host.save();await host.close();host=await createServer({port:0,public:true,autoTick:false,worldFile:path.join(temporary,'world.save.json')});const c=await client(host.url,'','Beta',identity);clients.push(c);assert.equal((await c.wait('welcome')).id,id);assert.deepEqual(host.getPlayers().find(r=>r.id===id).player.inventory,pack);const saved=fs.readFileSync(path.join(temporary,'world.save.json'),'utf8');assert(!saved.includes(identity),'raw bearer identity must not be stored on disk');});
 await check('private local lobbies reject empty keys, issue invite codes, and remain absent from public listings',async()=>{const privateHost=await createServer({port:0,autoTick:false,worldFile:path.join(temporary,'private.save.json')});try{assert(privateHost.invite.startsWith('SIRENS1.'));const data=JSON.parse(Buffer.from(privateHost.invite.slice(8),'base64url').toString());const wrong=await client(privateHost.url,'','No key');clients.push(wrong);await wrong.wait('error');const good=await client(privateHost.url,data.token,'Invited');clients.push(good);await good.wait('welcome');assert.equal((await(await fetch(privateHost.httpUrl+'servers')).json()).servers.length,0);}finally{await privateHost.close();}});
 await check('public directory registers authorized real hosts, exposes no keys, persists and expires listings',async()=>{let now=Date.now();const token='directory-test-key-only';directory=await createDirectory({port:0,token,file:path.join(temporary,'directory.json'),now:()=>now});const publicData=(await(await fetch(host.httpUrl+'servers')).json()).servers[0];assert(publicData.public);const unauthorized=await fetch(directory.url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(publicData)});assert.equal(unauthorized.status,403);const registered=await fetch(directory.url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(publicData)});assert.equal(registered.status,201);const listed=await(await fetch(directory.url)).json();assert.equal(listed.servers.length,1);assert(!JSON.stringify(listed).includes(token));await directory.close();directory=await createDirectory({port:0,token,file:path.join(temporary,'directory.json'),now:()=>now});assert.equal((await(await fetch(directory.url)).json()).servers.length,1);now+=180001;assert.equal((await(await fetch(directory.url)).json()).servers.length,0);});
 await check('unauthenticated sockets have a per-address budget, end after two seconds and leave room for twenty invited players',async()=>{const privateHost=await createServer({port:0,autoTick:false,worldFile:path.join(temporary,'preauth.save.json')}),held=[],invited=[];try{const key=JSON.parse(Buffer.from(privateHost.invite.slice(8),'base64url').toString()).token;
  // Linux and Windows route all of 127/8 to loopback; macOS needs an alias before a second local address exists.
  const probe=await upgrade(privateHost.port,'127.0.0.2'),attacker=probe.status==='101'?'127.0.0.2':'127.0.0.1';held.push(probe);if(attacker==='127.0.0.1')probe.s.destroy();
  for(let i=0;i<8&&held.filter(h=>h.status==='101'&&!h.s.destroyed).length<4;i++)held.push(await upgrade(privateHost.port,attacker));assert.equal(held.filter(h=>h.status==='101'&&!h.s.destroyed).length,4);
  assert.equal((await upgrade(privateHost.port,attacker)).status,'403','a fifth unauthenticated socket from one address is refused');
  if(attacker==='127.0.0.2'){for(let i=0;i<20;i++){const c=await client(privateHost.url,key,'Invited '+i);invited.push(c);await c.wait('welcome');}assert.equal(privateHost.getPlayers().filter(p=>p.connected).length,20,'invited players fill the world while unauthenticated sockets are held');}else console.log('NOTE second loopback address unavailable; per-address isolation was not exercised.');
  const open=held.filter(h=>h.status==='101');await Promise.all(open.map(h=>new Promise(r=>h.s.destroyed?r():h.s.once('close',r))));for(const h of open)assert(Date.now()-h.opened<3500,'silent unauthenticated sockets are terminated after the two-second join window');
  const again=await upgrade(privateHost.port,attacker);held.push(again);assert.equal(again.status,'101','released unauthenticated slots become available again');}finally{for(const h of held)h.s.destroy();for(const c of invited)c.close();await privateHost.close();}});
 await check('actions, joins and leaves mark the world changed so one tick sends one snapshot and saves are coalesced',async()=>{const file=path.join(temporary,'coalesce.save.json'),quiet=await createServer({port:0,public:true,autoTick:false,worldFile:file}),local=[],rename=fs.promises.rename;let writes=0;fs.promises.rename=async(from,to)=>{if(to===file)writes++;return rename(from,to);};try{
  for(let i=0;i<3;i++){const c=await client(quiet.url,'','Quiet '+i);local.push(c);await c.wait('welcome');}await delay(30);assert(local.every(c=>!c.messages.some(m=>m.type==='snapshot')),'a join waits for the next tick');quiet.tick();for(const c of local)await c.wait('snapshot');
  const count=()=>local.map(c=>c.messages.filter(m=>m.type==='snapshot').length),before=count();for(let i=0;i<10;i++){const seq=local[0].send('drop:not_an_item');await local[0].wait('ack',m=>m.seq===seq);}await delay(30);assert.deepEqual(count(),before,'rejected actions do not broadcast full snapshots');
  quiet.tick();await delay(50);assert.deepEqual(count(),before.map(n=>n+1),'one tick sends exactly one snapshot after ten changes');
  const identity=local[2].messages.find(m=>m.type==='welcome').identity;local[2].close();await delay(50);const start=writes;for(let i=0;i<8;i++){const c=await client(quiet.url,'','',identity);await c.wait('welcome');c.close();await new Promise(r=>c.socket.once('close',r));}
  assert(writes-start<=3,'eight reconnects wrote the world '+(writes-start)+' times');await delay(2300);assert(writes-start>=1,'a debounced save follows the reconnects');}finally{fs.promises.rename=rename;for(const c of local)c.close();await quiet.close();}});
 await check('per-address budgets bound reconnect churn and new survivor creation',async()=>{const busy=await createServer({port:0,public:true,autoTick:false,worldFile:path.join(temporary,'budget.save.json')});try{
  let created=0,denied='',keeper=null;for(let i=0;i<25&&!denied;i++){const c=await client(busy.url,'','Newcomer '+i),m=await outcome(c);if(m.type==='welcome'){created++;keeper=keeper||m.identity;c.close();await new Promise(r=>c.socket.once('close',r));}else denied=m.message;}
  assert.equal(created,20);assert.match(denied,/New survivors from this network address/);
  let joins=created+1;denied='';for(let i=0;i<20&&!denied;i++){const c=await client(busy.url,'','',keeper),m=await outcome(c);if(m.type==='welcome'){joins++;c.close();await new Promise(r=>c.socket.once('close',r));}else denied=m.message;}
  assert.match(denied,/Joins from this network address are arriving too quickly/);assert(joins>=30&&joins<=37,'join budget '+joins);}finally{await busy.close();}});
 await check('a full roster of 64 durable survivors admits a newcomer by replacing the survivor offline longest, keeping banned and connected survivors',async()=>{const file=path.join(temporary,'roster.save.json'),ownerToken='roster-test-owner-key',local=[];let full=await createServer({port:0,public:true,autoTick:false,worldFile:file,ownerToken,joinLimits:{joinBurst:200,survivorBurst:200}});try{
  const owner=await client(full.url,'','Roster Owner',null,ownerToken);local.push(owner);assert((await owner.wait('welcome')).owner);
  const made=[];for(let i=0;i<63;i++){const c=await client(full.url,'','Roster '+i);made.push(await c.wait('welcome'));c.close();await new Promise(r=>c.socket.once('close',r));}assert.equal(full.getPlayers().length,64);
  assert((await owner.chat('/ban '+made[0].id+' Roster test.')).ok);
  const newcomer=await client(full.url,'','Late Arrival');local.push(newcomer);await newcomer.wait('welcome');const ids=full.getPlayers().map(p=>p.id);
  assert.equal(ids.length,64);assert(ids.includes(made[0].id),'the banned survivor is kept');assert(!ids.includes(made[1].id),'the survivor offline longest is replaced');assert(ids.includes(made[2].id)&&ids.includes(owner.messages.find(m=>m.type==='welcome').id));
  const gone=await client(full.url,'','',made[1].identity);local.push(gone);assert.match((await gone.wait('error')).message,/Unknown survivor identity/);await full.close();
  full=await createServer({port:0,public:true,autoTick:false,worldFile:file,ownerToken});const saved=full.getPlayers().map(p=>p.id);assert.equal(saved.length,64);assert(saved.includes(made[0].id)&&!saved.includes(made[1].id),'the replacement and the ban survive a restart');
  const banned=await client(full.url,'','',made[0].identity);local.push(banned);assert.match((await banned.wait('error')).message,/banned/);}finally{for(const c of local)c.close();await full.close();}});
 console.log(passed+' multiplayer and directory checks passed.');
}finally{for(const c of clients)c.close();if(host)await host.close();if(directory)await directory.close();fs.rmSync(temporary,{recursive:true,force:true});}})().catch(error=>{console.error(error.stack);process.exitCode=1;});
